services:
  ssh-server:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:ssh-server-${STAGE}
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      - chess-engine
      - sqlite-db
    volumes:
      - sqlite-data:/data/db

  sqlite-db:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:sqlite-db-${STAGE}
    volumes:
      - sqlite-data:/data/db

  chess-engine:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:chess-engine-${STAGE}
    networks:
      - internal
    depends_on:
      - sqlite-db
    volumes:
      - sqlite-data:/data/db

volumes:
  sqlite-data:

networks:
  internal:
    driver: bridge