services:
  ssh-server:
    build:
      context: .  # build with root dir context so can access certs
      dockerfile: ./ssh-server/Dockerfile
      args:
        SSH_CHESS_SERVER_KEY_PATH: ${SSH_CHESS_SERVER_KEY_PATH}
        SSH_CHESS_CLIENT_KEY_PATH: ${SSH_CHESS_CLIENT_KEY_PATH}
    ports:
      - "${SSH_PORT}:22"
      - "${WEB_PORT}:80"
    networks:
      - internal
    depends_on:
      - chess-engine
      - sqlite-db
    volumes:
      - sqlite-data:/data/db

  sqlite-db:
    build: ./sqlite-db
    volumes:
      - sqlite-data:/data/db

  chess-engine:
    build: ./chess-engine
    networks:
      - internal
    depends_on:
      - sqlite-db
    volumes:
      - sqlite-data:/data/db

#  chessdotcom-sync:
#    build: ./chessdotcom-sync
#    networks:
#      - internal

volumes:
  sqlite-data:

networks:
  internal:
    driver: bridge