name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Makefile'
      - 'docker-compose.yml'
      - '.gitignore'
      - 'certs/**'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      ssh_server: ${{ steps.filter.outputs.ssh_server }}
      chess_engine: ${{ steps.filter.outputs.chess_engine }}
      sqlite_db: ${{ steps.filter.outputs.sqlite_db }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ssh_server:
              - 'ssh-server/**'
            chess_engine:
              - 'chess-engine/**'
            sqlite_db:
              - 'sqlite-db/**'

  deploy-to-server:
    needs: check_changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Ubuntu Server
        if: |
          needs.check_changes.outputs.ssh_server == 'true' ||
          needs.check_changes.outputs.chess_engine == 'true' ||
          needs.check_changes.outputs.sqlite_db == 'true'
        env:
          USER: ${{ secrets.USER }}
          IP: ${{ secrets.IP }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

          sshpass -p "${PASSWORD}" ssh -o StrictHostKeyChecking=no ${USER}@${IP} <<EOF
            set -e

            cd ~/ssh-chess
            git pull origin main

            # Stop the service, build, and restart it in detached mode
            make stop build start-detached
          EOF